USE AIRPORT
GO

INSERT INTO MANAGEMENT (Management_ID)
VALUES ('MAN1')

INSERT INTO MEMBER (Member_ID)
VALUES ('MEM1')

INSERT INTO PLANE(Plane_Number)
VALUES ('PL1')

INSERT INTO DESTINATION (Destination_ID)
VALUES ('CPT')

INSERT INTO FLIGHTS (Flight_Number)
VALUES ('FNPL1')

INSERT INTO BOOKING (Booking_Number)
VALUES ('BK1')

